### PR TITLE
Use Geometric Means for calculating the best Rows

### PR DESCRIPTION
**Pull request by CryZe**
When dealing with factors, arithmetic means are less accurate as geometric means, which is why the calculation should be done with a geometric mean.

### CODE REVIEW

**Comment by CryZe** [comment]
The Website shows an Application Error now. Looks like I might have introduced some Syntax Error. Hard to tell though without being able to debug it.

**Comment by Zamiell** [comment]
http://pastebin.com/YuBmw6Cb

Not sure what the issue is.

**Comment by dclaganiere** [comment]
Could you pull more lines? Default is only 100 and I think the part of the stack trace we want is deeper (I might be wrong on that)

**Comment by Zamiell** [comment]
I'll mess with it more when I get home from work.

**Comment by dclaganiere** [comment]
Found the issue: https://github.com/Automattic/monk/issues/114
I'll fix the package.json by switching to mongodb@~1.4, since we aren't using 2.0 features afaik.

**Comment by dclaganiere** [comment]
Undid revert of this; working fine!

**Pull request merged**
